steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/tech-challenge-ibovespa-new/ibovespa-repo/ibovespa-data-updater:latest-nuevo',
    '-f', 'cloudrun/Dockerfile',  # Ruta al Dockerfile
    '.'  # Contexto de construcción
  ]
images:
- 'us-central1-docker.pkg.dev/tech-challenge-ibovespa-new/ibovespa-repo/ibovespa-data-updater:latest-nuevo'
