steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t',
            'us-central1-docker.pkg.dev/tech-challenge-ibovespa-new/ibovespa-repo-new/ibovespa-data-final:latest-nuevo',
            '-f', 'cloudrun/Dockerfile', '.' ]
images:
  - 'us-central1-docker.pkg.dev/tech-challenge-ibovespa-new/ibovespa-repo-new/ibovespa-data-final:latest-nuevo'
